# Vežbe 2: PyTorch, tenzori i osnove linearne algebre

Na ovim vežbama uvodimo osnovne pojmove linearne algebre i povezujemo ih sa radom u biblioteci [PyTorch](https://pytorch.org/docs/stable/index.html).  
Cilj je da razumemo kako se podaci predstavljaju pomoću tenzora i kako se izvode osnovne operacije koje su važne za neuronske mreže.

In [37]:
# Import potrebnih biblioteka
import torch
import numpy as np

## 1. Skalari

Skalar predstavlja jedan broj.  
U PyTorch-u se i skalar predstavlja kao tenzor, ali sa samo jednim elementom.

In [38]:
# Kreirati dva skalara
x = torch.tensor(3.0)
y = torch.tensor(2.0)

print(x.dtype)
print(y.dtype)

# Izračunati zbir, proizvod, količnik i stepen
x + y,x * y,x / y,x ** y

torch.float32
torch.float32


(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

## 2. Vektori

Vektor možemo posmatrati kao niz skalarnih vrednosti fiksne dužine.  
U PyTorch-u je vektor jednodimenzioni tenzor.

In [39]:
# Kreirati vektor sa vrednostima od 0 do 2
x = torch.arange(3) #x = torch.arange(3, dtype=torch.float32)
print(x)

tensor([0, 1, 2])


In [40]:
# Prikazati element sa indeksom 2
x[2]

tensor(2)

In [41]:
# Odrediti dužinu vektora
len(x)

3

In [42]:
# Prikazati shape vektora
x.shape

torch.Size([3])

## 3. Matrice

Matrica je dvodimenziona struktura podataka.  
U PyTorch-u matrica je tenzor drugog reda, odnosno tenzor sa dve dimenzije.

In [43]:
# Kreirati tenzor sa vrednostima od 0 do 5
# Preoblikovati ga u matricu dimenzija 3 x 2
A = torch.arange(6).reshape(3, 2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [44]:
# Prikazati shape matrice
A.shape

torch.Size([3, 2])

In [45]:
# Prikazati transponovanu matricu A
A.T #A.T.shape

tensor([[0, 2, 4],
        [1, 3, 5]])

## 4. Tenzori

Tenzor je opštiji pojam i može imati više dimenzija.  
Na primer, skalar je 0D tenzor, vektor je 1D tenzor, matrica je 2D tenzor, a ovde ćemo prikazati i 3D tenzor.

In [46]:
# Kreirati 3D tenzor dimenzija 2 x 3 x 4
torch.arange(24).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

## 5. Različiti načini za kreiranje tenzora

Tenzori se u PyTorch-u mogu kreirati na još različitih načina:
- direktno iz liste podataka
- iz NumPy niza
- iz drugog tenzora
- pomoću funkcija za slučajne ili konstantne vrednosti

In [47]:
# Kreirati tenzor direktno iz liste podataka
# Nazvati ga x_data
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [48]:
# Kreirati NumPy niz na osnovu liste
# Zatim kreirati tenzor iz NumPy niza
np_array = np.array(data)

x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [49]:
# Kreirati tenzor popunjen jedinicama koji ima isti shape kao x_data
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor:\n{x_ones}\n")

# Kreirati tensor sa slučajnim vrednostima koji ima isti shape kao x_data
# Tip podataka postaviti na float
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor:\n{x_rand}\n")

Ones Tensor:
tensor([[1, 1],
        [1, 1]])

Random Tensor:
tensor([[0.2442, 0.9800],
        [0.5457, 0.0995]])



In [50]:
# Definisati shape tenzora
shape = (2, 3)

# Kreirati tenzor sa slučajnim vrednostima
rand_tensor = torch.rand(shape)

# Kreirati tenzor popunjen jedinicama
ones_tensor = torch.ones(shape)

# Kreirati tenzor popunjen nulama
zeros_tensor = torch.zeros(shape)

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.8234, 0.0205, 0.8910],
        [0.7936, 0.4070, 0.3044]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


## 5. Atributi tenzora

Svaki tenzor ima osnovne atribute koji nam govore:
- njegov shape
- tip podataka
- uređaj na kojem se tensor nalazi

In [51]:
# Kreirati tenzor dimenzija 3 x 4 sa slučajnim vrednostima
tensor = torch.rand(3, 4)

# Prikazati shape, tip podataka i uređaj
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## 6. Indeksiranje i slicing

Indeksiranje uzima jedan element, dok slicing uzima više elemenata (deo tenzora).

In [52]:
# Kreirati matricu dimenzija 4 x 4 sa vrednostima od 0 do 15 (tipa float)
tensor = torch.arange(16, dtype=torch.float32).reshape(4, 4)
tensor

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])

In [53]:
# Prikazati drugi red matrice
print(tensor[1])

# Prikazati poslednji red matrice
print(tensor[-1])

tensor([4., 5., 6., 7.])
tensor([12., 13., 14., 15.])


In [54]:
# Prikazati treću kolonu matrice
print(tensor[:, 2])

# Prikazati poslednju kolonu matrice
print(tensor[:, -1])

tensor([ 2.,  6., 10., 14.])
tensor([ 3.,  7., 11., 15.])


In [55]:
# Prikazati element u trećem redu i drugoj koloni
print(tensor[2, 1])

# Prikazati redove od indeksa 1 do 2
print(tensor[1:3])

tensor(9.)
tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [56]:
# Sve elemente prve kolone postaviti na 5
tensor[:, 0] = 5
tensor

tensor([[ 5.,  1.,  2.,  3.],
        [ 5.,  5.,  6.,  7.],
        [ 5.,  9., 10., 11.],
        [ 5., 13., 14., 15.]])

In [57]:
# Sve elemente poslednjeg reda postaviti na 0
tensor[-1, :] = 0
tensor

tensor([[ 5.,  1.,  2.,  3.],
        [ 5.,  5.,  6.,  7.],
        [ 5.,  9., 10., 11.],
        [ 0.,  0.,  0.,  0.]])

In [58]:
# Prva dva reda postaviti na vrednost 10
tensor[:2, :] = 10
tensor

tensor([[10., 10., 10., 10.],
        [10., 10., 10., 10.],
        [ 5.,  9., 10., 11.],
        [ 0.,  0.,  0.,  0.]])

## 7. Aritmetičke operacije nad tenzorima

Kada dva tenzora imaju isti shape, nad njima možemo vršiti osnovne aritmetičke operacije po elementima.

In [59]:
# Kreirati dva vektora
x = torch.tensor([1, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])

# Izračunati zbir, razliku, proizvod, količnik i stepen po elementima
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3,  4,  6, 10]),
 tensor([-1,  0,  2,  6]),
 tensor([ 2,  4,  8, 16]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1,  4, 16, 64]))

## 8. Skalarni proizvod (dot product)

Skalarni proizvod dva vektora dobija se tako što:
- pomnožimo odgovarajuće elemente
- zatim saberemo dobijene proizvode

In [60]:
# Kreirati vektor x sa vrednostima od 0 do 2 tipa float32
x = torch.arange(3, dtype=torch.float32)
print(x)

# Kreirati vektor y popunjen jedinicama tipa float32
y = torch.ones(3, dtype=torch.float32)
print(y)

tensor([0., 1., 2.])
tensor([1., 1., 1.])


In [61]:
# Izračunati skalarni proizvod vektora x i y
torch.dot(x, y)

tensor(3.)

## 9. Množenje matrice i vektora

Kod množenja matrice i vektora:
- broj kolona matrice mora biti jednak broju elemenata vektora
- rezultat je novi vektor

In [62]:
# Kreirati matricu A dimenzija 2 x 2
A = torch.tensor([[1,2],
                  [3,4]])

# Kreirati vektor x dužine 2
x = torch.tensor([5,6])

# Prikazati shape matrice A i vektora x
A.shape, x.shape

(torch.Size([2, 2]), torch.Size([2]))

In [63]:
# Izračunati proizvod matrice A i vektora x
A @ x #torch.mv(A, x)

tensor([17, 39])

## 10. Množenje matrica

Kod množenja matrica:
- broj kolona prve matrice mora biti jednak broju redova druge matrice
- rezultat je nova matrica

In [64]:
# Kreirati matricu A dimenzija 2 x 3
A = torch.tensor([[0.0, 1.0, 2.0],
                  [3.0, 4.0, 5.0]])

# Kreirati matricu B dimenzija 3 x 4 popunjenu jedinicama
B = torch.ones((3, 4))

# Prikazati shape matrica A i B
A.shape, B.shape

(torch.Size([2, 3]), torch.Size([3, 4]))

In [65]:
# Izračunati proizvod matrica A i B
A @ B #torch.mm(A, B)

tensor([[ 3.,  3.,  3.,  3.],
        [12., 12., 12., 12.]])

## 11. Reduction: suma i srednja vrednost

Redukcija predstavlja operaciju kojom tenzor svodimo na manju dimenziju, na primer sabiranjem ili računanjem proseka.

In [66]:
# Kreirati matricu A dimenzija 3 x 2
A = torch.arange(6, dtype=torch.float32).reshape(3, 2)
A

tensor([[0., 1.],
        [2., 3.],
        [4., 5.]])

In [67]:
# Prikazati sumu po osi 0
print(A.sum(axis=0))

# Prikazati sumu po osi 1
print(A.sum(axis=1))

tensor([6., 9.])
tensor([1., 5., 9.])


In [68]:
# Izracunati sumu svih elemenata i pretvoriti rezultat u Python broj
agg=A.sum()
agg_item=agg.item()
print(agg_item, type(agg_item))

15.0 <class 'float'>


In [69]:
# Izračunati srednju vrednost elemenata matrice A
# Uporediti je sa količnikom sume svih elemenata i ukupnog broja elemenata
A.mean(), A.sum() / A.numel()

(tensor(2.5000), tensor(2.5000))